"""empty message

Revision ID: 2e941b1083d4
Revises: efcda444d2e1
Create Date: 2020-09-08 19:10:14.771988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e941b1083d4'
down_revision = 'efcda444d2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'date')
    # ### end Alembic commands ###
